UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00082';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00086';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00142';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00203';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00234';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00275';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00271';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00182';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00110';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00027';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00194';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00012';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00183';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00209';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00045';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00031';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00264';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00226';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00101';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00013';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00044';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00207';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00047';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00061';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00190';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00202';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00285';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00137';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00268';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00030';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00119';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00124';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00025';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00177';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00043';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00140';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00222';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00178';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00108';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00040';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00294';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00131';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00006';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00117';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00022';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00032';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00276';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00286';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00265';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00139';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00132';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00141';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00218';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00073';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00277';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00297';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00087';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00169';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00220';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00041';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00162';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00172';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00107';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00046';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00064';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00096';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00175';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00213';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00281';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00252';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00018';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00023';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00130';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00224';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00021';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00114';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00171';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00109';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00133';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00120';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00016';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00287';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00180';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00094';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00219';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00037';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00004';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00260';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00161';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00188';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00052';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00200';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00055';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00125';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00057';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00206';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00160';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00211';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00266';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00105';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00122';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00282';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00239';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00184';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00102';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00290';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00256';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00112';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00283';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00284';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00138';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00242';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00024';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00066';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00167';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00168';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00179';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00049';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00173';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00060';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00269';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00078';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00236';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00092';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00229';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00062';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00088';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00147';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00058';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00170';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00051';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00165';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00199';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00181';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00151';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00228';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00241';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00163';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00262';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00089';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00070';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00302';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00259';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00159';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00189';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00251';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00150';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00080';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00063';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00193';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00103';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00250';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00257';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00115';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00068';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00054';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00149';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00005';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00042';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00214';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00255';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00238';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00212';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00248';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00201';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00053';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00198';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00272';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00002';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00003';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00069';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00036';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00116';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00293';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00100';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00258';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00263';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00244';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00233';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00157';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00270';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00292';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00017';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00145';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00033';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00007';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00237';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00227';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00243';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00232';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00235';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00028';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00185';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00221';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00254';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00240';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00077';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00038';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00085';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00065';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00208';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00231';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00204';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00253';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00056';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00230';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00081';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00186';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00215';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00093';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00246';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00146';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00011';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00158';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00048';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00015';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00195';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00148';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00191';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00067';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00072';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00050';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00280';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00098';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00156';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00174';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00019';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00001';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00144';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00245';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00205';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00192';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00095';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00111';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00084';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00288';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00026';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00303';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00129';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00225';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00035';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00079';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00274';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00128';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00298';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00296';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00295';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00210';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00126';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00014';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00134';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00249';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00008';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00099';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00091';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00075';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00217';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00083';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00104';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00135';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00261';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00216';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00176';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00187';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00074';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00020';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JOEL ESTORCO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00071';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00097';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00123';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00279';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00118';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00143';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CHRISTIAN SESALDO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00223';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00164';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00196';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00267';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00301';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00034';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00090';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00121';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00278';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00300';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00304';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00039';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00166';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00010';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00289';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00029';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'RAFFY BAGUIO' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00009';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00153';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00155';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00127';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JED MELENDREZ' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00154';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'CARL MANGRUBAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00106';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ALFRED SABERON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00136';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'MICHAEL DE GUZMAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00059';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'JASON' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00299';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'ROEL CATALAN' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00247';
UPDATE employees SET supervisor_id = (SELECT id FROM supervisors WHERE name = 'HARRY EYA' LIMIT 1) WHERE employee_id = 'LB-MANDAUE-00197';