-- 1. Add username and password_hash to supervisors table
ALTER TABLE supervisors 
ADD COLUMN IF NOT EXISTS username VARCHAR(255) UNIQUE,
ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);

-- 2. Populate default usernames based on their name, and a default password 'supervisor123'
-- The hash below is for 'supervisor123'
UPDATE supervisors 
SET username = LOWER(REPLACE(name, ' ', '')),
    password_hash = '$2b$10$BmrcfNJThFknHq/oN.liPuAjmWh28XJBCTjUUiqRym2EKTFKxYSHW'
WHERE username IS NULL;

-- 3. Create supervisor_locations table for real-time tracking
CREATE TABLE IF NOT EXISTS supervisor_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id BIGINT REFERENCES supervisors(id) ON DELETE CASCADE,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    heading DECIMAL(5, 2), -- Optional: direction they are facing
    speed DECIMAL(5, 2), -- Optional: speed in m/s
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(supervisor_id) -- Ensure only one active location row per supervisor
);

-- Enable RLS
ALTER TABLE supervisor_locations ENABLE ROW LEVEL SECURITY;

-- Allow public to select and insert/update to supervisor_locations (for simplicity, but can restrict later)
DROP POLICY IF EXISTS supervisor_locations_all_public ON supervisor_locations;
CREATE POLICY supervisor_locations_all_public ON supervisor_locations
    FOR ALL TO public USING (true) WITH CHECK (true);

-- Trigger to auto-update last_updated
CREATE OR REPLACE FUNCTION update_supervisor_location_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_updated = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_supervisor_location_timestamp ON supervisor_locations;
CREATE TRIGGER trigger_supervisor_location_timestamp
    BEFORE UPDATE ON supervisor_locations
    FOR EACH ROW
    EXECUTE FUNCTION update_supervisor_location_timestamp();

-- 4. Enable Realtime for supervisor_locations
-- Note: You might still need to go to Supabase Dashboard -> Database -> Replication and enable Realtime for this table.
ALTER PUBLICATION supabase_realtime ADD TABLE supervisor_locations;
